### ISSUE TITLE
CreateContainerConfigError

### ISSUE THREAD

**Issue by sriniabhinavraj** [keptn-sandbox/generic-executor-service#1]
Getting an error on running kubectl apply for this service:
Steps:
1 Cloned Generic-executor-service into local Ubuntu machine where keptn projects are stored
2. Ran kubectl apply -f deploy/service.yaml
deployment.apps/generic-executor-service created
service/generic-executor-service created
deployment.apps/generic-executor-service-distributor created
3. Ran  kubectl -n keptn get deployment generic-executor-service -o wide 
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                 IMAGES                                        SELECTOR
generic-executor-service   0/1     1            0           12m   generic-executor-service   grabnerandi/generic-executor-service:latest   run=generic-executor-service
4. Ran kubectl -n keptn get pods -l run=generic-executor-service
NAME                                        READY   STATUS                       RESTARTS   AGE
generic-executor-service-6d7898db7d-8759p   0/1     CreateContainerConfigError   0          13m

**Comment by grabnerandi** [comment]
HI. Sorry for the late reply. Seems the readme linked to the wrong container image. Please simply use the "latest" tag to get this running

**Comment by sriniabhinavraj** [comment]
Not a problem - thanks Andreas
